# Custom Language File for Launcher Customizer

[ejs.app]
title = "openMCSync"

[ejs.landing]
mediaGitHubURL = "https://damp11113.xyz/"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "#"

[ejs.settings]
sourceGithubLink = "https://github.com/DPSoftware-Foundation/openMCSync"
supportLink = "https://damp11113.xyz/donate"

[ejs.welcome]
welcomeHeader = "Welcome to openMCSync"
welcomeDescription = ""
welcomeDescCTA = ""
